### ISSUE TITLE
Show the next person in the cooldown alert

### ISSUE THREAD

**Issue by henrik** [stoft/mobbur#18]
When mobbing via screensharing, there's no second display to show Mobbur, so we run it in a background tab.

It would be great if the popup notifications would show who is next so we don't have to switch to the Mobbur tab to find out.

(I might contribute this some time in the future, but please feel free to do it without me if anyone else is inclined.)

**Comment by stoft** [comment]
Ty, good feedback! I'll see if I can get it done soonish, it's a bit trickier since I've modeled Team and Timer separately and the notification is triggered from the timer which doesn't know the current team state. I.e. it will need a bit of refactoring.

**Comment by henrik** [comment]
:thumbsup:
