### ISSUE TITLE
Renaming/Name rules

### ISSUE THREAD

**Issue by Mousaka** [stoft/mobbur#2]
If you name someone to an empty string, e.g. if you accidentally press enter immediately when naming a new member, there seems to be no way to rename the unnamed team member since the name element in the list will have no size so you cannot click it.

Suggestion for solution would be to either forbid empty names or make the empty-name-element click-able somehow so you can rename it afterwards.

Cheers!

**Comment by stoft** [comment]
Thank you! Will fix immediately! :)

**Comment by Mousaka** [comment]
nice response time on the issue ^^ :+1: 

I noticed however that it is still possible to end up in the same situation if you name your self any number of spaces

**Comment by stoft** [comment]
@Mousaka good catch! Should be fixed now. 😸
