### ISSUE TITLE
Possibility to reset the timer

### ISSUE THREAD

**Issue by stoft** [stoft/mobbur#5]
As  a user I'd like to be able to easily reset the timer in case we get a "false start" or similar.

**Comment by stoft** [comment]
@kek I believe you requested this, correct?

**Comment by kek** [comment]
Yes.

**Comment by stoft** [comment]
@kek ok, let me know what you think. I've now added a simple reset button that's only visible when paused (quick command 'r' as well).

**Comment by kek** [comment]
I think it looks really nice now!
